name: Trading Bot US Test

on:
  schedule:

jobs:
  run-us-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Chrome version
        run: google-chrome --version

      - name: Run US Bot
        run: python main_us.py
        env:
          ROUTE_LLM_API_KEY: ${{ secrets.ROUTE_LLM_API_KEY }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SENDER: ${{ secrets.SMTP_SENDER }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_RECIPIENT: ${{ secrets.SMTP_RECIPIENT }}
